// Code generated by goctl. DO NOT EDIT.
package types

type RequestConstUser struct {
}

type ResponseConstUser struct {
	Num int `json:"num"`
}

type RequestMultiUser struct {
}

type ResponseMultiUser struct {
	Num int `json:"num"`
}

type RequestSendTx struct {
}

type ResponseSendTx struct {
	Num int `json:"num"`
}
